### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jorgegonzalez** [jorgegonzalez/rice#1]
**General**
- [ ] Check for OS and run appropriate ascii
- [ ] Add those ascii to osart
- [ ] Return object from config
- [ ] Add option for bar in config
- [ ] Check window manager and desktop environment
- [ ] Terminal font
- [ ] Test in Linux VMs
- [ ] Add cli options for every config
- [ ] Change position of ascii 
- [ ] Option for custom ascii (new architecture at this point)
- [ ] Get wallpaper and print it
- [ ] Option for custom image
- [ ] Option for screenshot of terminal output

**Comment by lclarke5** [comment]
"Test in Linux VMs"


![image](https://user-images.githubusercontent.com/12300764/36362433-b805401a-1502-11e8-9b74-9a206516a45a.png)


Works in Linux mint so should work in other debian OS.

Issues Related to OS:
Terminal is undefined.
Doesn't detect non integrated gpu.
Doesn't detect battery percentage.

**Comment by jorgegonzalez** [comment]
Also not detecting the shell version. Will create new issues soon. Thanks for this!

**Comment by jorgegonzalez** [comment]
@lclarke5 Small update, but the proper ASCII art should print now.

**Comment by lclarke5** [comment]
It does.
